baseURL = "https://cloudnativego.com"
languageCode = "en-us"
title = "Cloud Native Go!"
metaDataFormat = "yaml"
theme = "kube"
DefaultContentLanguage = "en"
description = "Cloud Native Infrastruture and Applications"
Paginate = 4

[Params]
  RSSLink = "/index.xml"
  author = "CloudNativeGo.com" # add your company name
  github = "CloudNativeInfra" # add your github profile name
  twitter = "jimmysongio" # add your twitter profile
  email = "jimmysong@jimmysong.io"
  dateFormat = "January 2, 2006"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
